SET MODE MYSQL;
SET IGNORECASE = TRUE;

-- -----------------------------------------------------
-- TABLE `CHARITY`
-- -----------------------------------------------------

DROP TABLE IF EXISTS CANDIDATES;
DROP TABLE IF EXISTS PERSONAL_INFORMATION;


CREATE TABLE IF NOT EXISTS CANDIDATES
(
    ID              INTEGER AUTO_INCREMENT NOT NULL,
    EMAIL           VARCHAR(200)          NOT NULL UNIQUE,
    FIRST_NAME           VARCHAR(200)            NOT NULL,
    SURNAME         VARCHAR(200)         NOT NULL,
    COMPANY_NAME   VARCHAR(5)             NOT NULL,
    PRIMARY KEY (`ID`)
)
    ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS CANDIDATE_INFORMATION (
    ID INTEGER AUTO_INCREMENT NOT NULL,
    CID INTEGER NOT NULL,
    NI INTEGER NOT NULL,
)
    ENGINE = INNODB;


